### ISSUE TITLE
How do you import into servoy?

### ISSUE THREAD

**Issue by simon-p-r** [Servoy/example-solutions#1]
Hi 

Just tried cloning into a new servoy / eclipse workspace using egit however the project cannot find the resources folder which includes the datasources.

Thanks
Simon

**Comment by seanthomasdevlin** [comment]
Hi Simon,

Thanks for your interest in the examples from the 8.1 launch webinar series.

By far the easiest way to import is is from the binary distributions  on the [releases page](https://github.com/Servoy/example-solutions/releases)

The resources project will created/appended to during the import.
If you want to run from source, then clone the repository. Depending on where you have cloned to, you may need to do a general **eclipse** import into workspace. (File > import > existing projects)

Hope this helps.

Best,
Sean

**Comment by simon-p-r** [comment]
Thanks @seanthomasdevlin for your help!  I thought I was missing some Egit trick to import project into IDE!

Best regards
Simon
